require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/MethodLength:
  Exclude:
    - 'test/**/test_*.rb'

Style/SingleLineMethods:
  Exclude:
    - 'test/**/test_*.rb'
